print("                          CV")
print("Nume/prenume:                 Țihosnchi Alexandra")
print("Data/luna/anul nasterii:      23.09.2004")
print("Studii:                       Liceul Teoretic Mihai Eminescu")
print("                              Casa poloneză din mun.Bălți")
print("Succese și reușite obținute:  Numeroase diplome de excelența în cadrul activitaților extracuriculare și extrașcolare.")
print("                              Diplome acordate în urma activitaților de voluntariat.")
print("Competențe adiționate:        Microsoft ofice, internet, Pascal, python")
print("Cunoasterea limbii:           Posed limbile: romana, rusa, engleza, franceza, poloneza, spaniola")
print("Interese:                     Muzica, literatura, sportul, turismul, dansurile, gatitul")
print("Adresa:                       mun.Bălti Voluntarilor 59/31")
print("Telefon de contact:           +37369791389")
print("E-mail:                       alexandratihonschi@gmail.com")